spring:
  datasource:
    url: jdbc:postgresql://localhost:9098/postgres
    username: postgres
    password: 3e659C08
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true