spring:
  datasource:
    url: jdbc:postgresql://localhost:9097/postgres?currentSchema=public
    username: postgres
    password: 3e659C08
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
#    baseline-on-migrate: true

#logging:
#  level:
#    org.flywaydb.core: DEBUG